# Generated by Django 2.2 on 2020-11-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, choices=[('MIS', 'MIS'), ('ZM', 'ZM'), ('PC', 'PC'), ('PM', 'PM')], max_length=30, null=True),
        ),
    ]
