# Generated by Django 2.2 on 2020-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201111_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('PM', 'PM'), ('ZM', 'ZM'), ('MIS', 'MIS')], max_length=30, null=True),
        ),
    ]
