# Generated by Django 2.2 on 2020-11-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201111_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, choices=[('MIS', 'MIS'), ('PC', 'PC'), ('PM', 'PM'), ('ZM', 'ZM')], max_length=30, null=True),
        ),
    ]
