# Generated by Django 2.2 on 2020-11-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201111_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, choices=[('PM', 'PM'), ('ZM', 'ZM'), ('PC', 'PC'), ('MIS', 'MIS')], max_length=30, null=True),
        ),
    ]
