# Generated by Django 3.1 on 2020-11-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_number', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('hq', models.CharField(blank=True, max_length=1000, null=True)),
                ('govt_id_proof_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('govt_id_proof_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('father_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('address', models.TextField()),
                ('pincode', models.PositiveIntegerField()),
                ('ssc_region', models.CharField(max_length=1000)),
                ('centre_type', models.CharField(max_length=1000)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centre', to='centre.operator')),
            ],
        ),
    ]
