# Generated by Django 3.1 on 2020-11-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_auto_20201122_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='operator',
        ),
        migrations.AddField(
            model_name='operator',
            name='centre',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='centre.centre'),
            preserve_default=False,
        ),
    ]
