# Generated by Django 3.1 on 2020-11-21 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('file', models.FileField(upload_to='excel_files')),
                ('update_file', models.BooleanField(default=False)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('errors_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=5000)),
                ('exam_start', models.DateField()),
                ('exam_end', models.DateField()),
                ('exam_on', models.DateField()),
                ('shift1', models.CharField(max_length=1000)),
                ('shift1_timing', models.TimeField()),
                ('shift2', models.CharField(max_length=1000)),
                ('shift2_timing', models.TimeField()),
                ('shift3', models.CharField(max_length=1000)),
                ('shift3_timing', models.TimeField()),
                ('max_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('removed', models.BooleanField(default=False)),
                ('removed_ts', models.DateTimeField(blank=True, null=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='centre.centre')),
                ('pc', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_pc', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_pm', to=settings.AUTH_USER_MODEL)),
                ('zm', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_zm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-insert_ts'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_cam_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('last_exam_observations', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=1000, null=True)),
                ('rate', models.PositiveIntegerField(blank=True, null=True)),
                ('centre_type', models.CharField(blank=True, choices=[('old', 'old'), ('new', 'new'), ('permanent_installed', 'permanent installed'), ('puneet_mittal', 'puneet mittal'), ('rahul_bansal', 'rahul bansal')], max_length=1000, null=True)),
                ('centre_open_time', models.TimeField(blank=True, null=True)),
                ('centre_close_time', models.TimeField(blank=True, null=True)),
                ('venue_head_contacted_by_vendor', models.BooleanField(blank=True, default=False, null=True)),
                ('centre_visited_by_vendor', models.BooleanField(blank=True, default=False, null=True)),
                ('disputed_centre', models.BooleanField(blank=True, default=False, null=True)),
                ('wiring_status', models.CharField(blank=True, choices=[('started', 'started'), ('completed', 'completed')], max_length=1000, null=True)),
                ('camera_status', models.CharField(blank=True, choices=[('started', 'started'), ('completed', 'completed')], max_length=1000, null=True)),
                ('dvr_status', models.BooleanField(blank=True, default=False, null=True)),
                ('live_feed_operational', models.CharField(blank=True, choices=[('started', 'started'), ('completed', 'completed')], max_length=1000, null=True)),
                ('comments_for_installation', models.TextField(blank=True, null=True)),
                ('installation_status', models.CharField(blank=True, choices=[('disputed', 'disputed'), ('work_in_progress', 'work in progress'), ('installation_complete', 'installation complete'), ('centre_live', 'centre live'), ('offline_live', 'offline live'), ('pending', 'pending')], max_length=1000, null=True)),
                ('total_camera_installed', models.PositiveIntegerField(blank=True, null=True)),
                ('total_camera_used', models.PositiveIntegerField(blank=True, null=True)),
                ('total_camera_count', models.PositiveIntegerField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('disputed', 'disputed'), ('work_in_progress', 'work in progress'), ('installation_complete', 'installation complete'), ('centre_live', 'centre live'), ('offline_live', 'offline live'), ('pending', 'pending')], max_length=1000, null=True)),
                ('ready_for_qc', models.BooleanField(blank=True, default=False, null=True)),
                ('qc_date', models.DateField(blank=True, null=True)),
                ('qc_time_slot', models.CharField(blank=True, max_length=1000, null=True)),
                ('pc_comments_for_qc', models.TextField(blank=True, null=True)),
                ('qc_status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending_at_dm', 'Pending at DM'), ('pending', 'Pending')], max_length=1000, null=True)),
                ('reason_qc', models.TextField(blank=True, null=True)),
                ('count_of_qc_requests', models.PositiveIntegerField(default=0)),
                ('qc_percentage', models.CharField(blank=True, choices=[('0', '0'), ('25', '25'), ('50', '50'), ('100', '100')], max_length=100, null=True)),
                ('ready_for_mock', models.BooleanField(default=False)),
                ('mock_date', models.DateField(blank=True, null=True)),
                ('mock_status', models.CharField(blank=True, choices=[('MP', 'Mock Pass'), ('MF', 'Mock Fail'), ('PAD', 'Pending at DM'), ('MP', 'Mock Pending')], max_length=1000, null=True)),
                ('mock_time_slot', models.TimeField(blank=True, null=True)),
                ('pc_comments_for_mock', models.TextField(blank=True, null=True)),
                ('reason_mock', models.TextField(blank=True, null=True)),
                ('count_of_mock_requests', models.PositiveIntegerField(default=0)),
                ('mock_percentage', models.CharField(blank=True, choices=[('', ''), ('0', '0'), ('25', '25'), ('50', '50'), ('100', '100')], max_length=1000, null=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='mis.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=1000)),
                ('row', models.PositiveIntegerField()),
                ('value', models.TextField()),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mis.excel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProjectMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=1000)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
